2025-05-04 09:23:30,218  INFO      werkzeug — [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.245.128.60:5000
2025-05-04 09:23:30,220  INFO      werkzeug — [33mPress CTRL+C to quit[0m
2025-05-04 09:23:30,227  INFO      werkzeug —  * Restarting with stat
2025-05-04 09:23:32,470  WARNING   werkzeug —  * Debugger is active!
2025-05-04 09:23:32,485  INFO      werkzeug —  * Debugger PIN: 660-035-175
2025-05-04 09:23:38,119  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 09:23:38,191  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 09:23:38] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 09:23:38,497  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 09:23:38] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-05-04 09:23:38,573  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 09:23:38] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-05-04 09:23:38,703  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 09:23:38] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-05-04 09:23:39,363  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 09:23:39] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 09:24:03,030  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 09:24:03] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 09:24:51,992  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 09:24:52,095  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 09:24:52] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 09:24:52,196  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 09:24:52] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-05-04 09:24:52,197  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 09:24:52] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-05-04 09:24:52,381  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 09:24:52] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-05-04 09:24:52,764  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 09:24:52] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 09:35:08,600  INFO      werkzeug —  * Detected change in 'C:\\Users\\Sbongakonke Sfiso\\OneDrive - University of KwaZulu-Natal\\Desktop\\3D Objects\\email_sender_app\\app.py', reloading
2025-05-04 09:35:09,444  INFO      werkzeug —  * Restarting with stat
2025-05-04 09:35:12,901 | WARNING  | werkzeug |  * Debugger is active!
2025-05-04 09:35:12,918 | INFO     | werkzeug |  * Debugger PIN: 660-035-175
2025-05-04 09:35:25,147 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:35:25] "GET / HTTP/1.1" 200 -
2025-05-04 09:35:25,456 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:35:25] "[36mGET /static/icons/icon1.JPG HTTP/1.1[0m" 304 -
2025-05-04 09:35:25,570 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:35:25] "[36mGET /static/icons/googe.png HTTP/1.1[0m" 304 -
2025-05-04 09:35:28,669 | INFO     | werkzeug | 10.245.128.60 - - [04/May/2025 09:35:28] "GET / HTTP/1.1" 200 -
2025-05-04 09:35:28,728 | INFO     | werkzeug | 10.245.128.60 - - [04/May/2025 09:35:28] "GET /static/icons/icon1.JPG HTTP/1.1" 200 -
2025-05-04 09:35:28,744 | INFO     | werkzeug | 10.245.128.60 - - [04/May/2025 09:35:28] "GET /static/icons/googe.png HTTP/1.1" 200 -
2025-05-04 09:35:28,931 | ERROR    | __main__ | Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 09:35:28,954 | INFO     | werkzeug | 10.245.128.60 - - [04/May/2025 09:35:28] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
2025-05-04 09:35:31,885 | INFO     | werkzeug | 10.245.128.60 - - [04/May/2025 09:35:31] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:35:42,303 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:35:42] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:38:06,771 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:38:06] "[32mGET /oauth2callback?state=ElhaMAgSxwdx7HpEMXNziukcagRXfT&code=4/0Ab_5qlnQ6Q-D2XV2v1cGkDPDo5qblAiwg1QIvHk1WLsi_KjKbfvv6oRQTb6Jod4PKh_nqg&scope=email%20profile%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=consent HTTP/1.1[0m" 302 -
2025-05-04 09:38:06,793 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:38:06] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:40:22,840 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:40:22] "[32mGET /oauth2callback?state=R9BHU4Gl1Te5SjZ5rdz3AqzDLMmLRR&code=4/0Ab_5qlkCS5Q_Jj0vT4C7eo_c5Ybr4hBQtsxnlPt0AY008PoOI5F22L8drhkb5yA4Ag0gig&scope=email%20profile%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=consent HTTP/1.1[0m" 302 -
2025-05-04 09:40:23,384 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:40:23] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:46:40,276 | INFO     | werkzeug | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-04 09:46:40,277 | INFO     | werkzeug | [33mPress CTRL+C to quit[0m
2025-05-04 09:46:40,281 | INFO     | werkzeug |  * Restarting with stat
2025-05-04 09:46:42,374 | WARNING  | werkzeug |  * Debugger is active!
2025-05-04 09:46:42,386 | INFO     | werkzeug |  * Debugger PIN: 660-035-175
2025-05-04 09:47:35,630 | INFO     | werkzeug | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-04 09:47:35,631 | INFO     | werkzeug | [33mPress CTRL+C to quit[0m
2025-05-04 09:47:35,635 | INFO     | werkzeug |  * Restarting with stat
2025-05-04 09:47:37,704 | WARNING  | werkzeug |  * Debugger is active!
2025-05-04 09:47:37,717 | INFO     | werkzeug |  * Debugger PIN: 660-035-175
2025-05-04 09:47:43,614 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:47:43] "GET / HTTP/1.1" 200 -
2025-05-04 09:47:44,077 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:47:44] "[36mGET /static/icons/icon1.JPG HTTP/1.1[0m" 304 -
2025-05-04 09:47:44,227 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:47:44] "[36mGET /static/icons/googe.png HTTP/1.1[0m" 304 -
2025-05-04 09:47:53,591 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:47:53] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:48:32,445 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:48:32] "[32mGET /oauth2callback?state=Jog4qsUdirIgs7xaEiBVOvQHRI8v6D&code=4/0Ab_5qlm0dtY_p56A7u2-pnQ9ihWwL4IiSp_abSCAV2K-Hp9ABAkKZ708BJCGjhZcKsHYDg&scope=email%20profile%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=consent HTTP/1.1[0m" 302 -
2025-05-04 09:48:32,460 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:48:32] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:48:57,185 | ERROR    | __main__ | OAuth callback failed
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 410, in oauth2callback
    flow.fetch_token(authorization_response=auth_response)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\google_auth_oauthlib\flow.py", line 285, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 271, in fetch_token
    self._client.parse_request_uri_response(
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\web_application.py", line 220, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 272, in parse_authorization_code_response
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
2025-05-04 09:48:57,225 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:48:57] "[32mGET /oauth2callback?state=7WV8CziuRXgBltq0cbUlpAzBRRGQSB&code=4/0Ab_5qlnf_cuInsyfIIdPa7cGitR3r_48TCjkOOY6YzZfXAlDmhoQpdYH7WHuQ3hqnPalfA&scope=email%20profile%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=consent HTTP/1.1[0m" 302 -
2025-05-04 09:48:57,248 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:48:57] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:49:30,538 | ERROR    | __main__ | OAuth callback failed
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 410, in oauth2callback
    flow.fetch_token(authorization_response=auth_response)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\google_auth_oauthlib\flow.py", line 285, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 271, in fetch_token
    self._client.parse_request_uri_response(
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\web_application.py", line 220, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 272, in parse_authorization_code_response
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
2025-05-04 09:49:30,542 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:49:30] "[32mGET /oauth2callback?state=5uHFtRq18ffH1NG1SQjw6ETW4pYDpP&code=4/0Ab_5qlkhXfEtvuI43JCsjLrGuIYn6GhM9mtceUrsE02JYlrUMP6AHuNmNVmolOfxLFi_JQ&scope=email%20profile%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=consent HTTP/1.1[0m" 302 -
2025-05-04 09:49:30,550 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:49:30] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:54:47,618 | INFO     | werkzeug |  * Detected change in 'C:\\Users\\Sbongakonke Sfiso\\OneDrive - University of KwaZulu-Natal\\Desktop\\3D Objects\\email_sender_app\\app.py', reloading
2025-05-04 09:54:48,217 | INFO     | werkzeug |  * Restarting with stat
2025-05-04 09:54:51,471 | WARNING  | werkzeug |  * Debugger is active!
2025-05-04 09:54:51,486 | INFO     | werkzeug |  * Debugger PIN: 660-035-175
2025-05-04 09:57:14,043 | INFO     | werkzeug | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-04 09:57:14,044 | INFO     | werkzeug | [33mPress CTRL+C to quit[0m
2025-05-04 09:57:14,048 | INFO     | werkzeug |  * Restarting with stat
2025-05-04 09:57:16,821 | WARNING  | werkzeug |  * Debugger is active!
2025-05-04 09:57:16,834 | INFO     | werkzeug |  * Debugger PIN: 660-035-175
2025-05-04 09:57:23,881 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:57:23] "GET / HTTP/1.1" 200 -
2025-05-04 09:57:24,263 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:57:24] "[36mGET /static/icons/icon1.JPG HTTP/1.1[0m" 304 -
2025-05-04 09:57:24,343 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:57:24] "[36mGET /static/icons/googe.png HTTP/1.1[0m" 304 -
2025-05-04 09:57:28,836 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:57:28] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:58:35,411 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:58:35] "[32mGET /oauth2callback?state=nsBVWQcOarEXMoN5gvR5eioWUprpkb&code=4/0Ab_5qllZtvBxn-sm2xIGxeLgZ8xIU8HHAm2T7lgpN0GUeN5IqElEALzPrAqBNorB1mrgcw&scope=email%20profile%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=consent HTTP/1.1[0m" 302 -
2025-05-04 09:58:35,422 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 09:58:35] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 09:59:43,445 | INFO     | googleapiclient.discovery_cache | file_cache is only supported with oauth2client<4.0.0
2025-05-04 10:00:45,350 | ERROR    | __main__ | OAuth callback failed
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 419, in oauth2callback
    userinfo = oauth2.userinfo().get().execute()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
                        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
                          ^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\httplib2\__init__.py", line 1366, in _conn_request
    conn.connect()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\httplib2\__init__.py", line 1158, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:989: The handshake operation timed out
2025-05-04 10:00:45,395 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 10:00:45] "[32mGET /oauth2callback?state=WwbiFX3JJOiuCs0xrHx7e7ZrvntphY&code=4/0Ab_5qlmTGHH0XC5RrjNxafFuTtMPeOXSqRwY1OrOOw49VIftS8XSbHZhUWt1xWCzE8M9fw&scope=email%20profile%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=consent HTTP/1.1[0m" 302 -
2025-05-04 10:00:45,710 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 10:00:45] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 10:08:42,025 | INFO     | werkzeug | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-04 10:08:42,026 | INFO     | werkzeug | [33mPress CTRL+C to quit[0m
2025-05-04 10:08:42,032 | INFO     | werkzeug |  * Restarting with stat
2025-05-04 10:08:44,207 | WARNING  | werkzeug |  * Debugger is active!
2025-05-04 10:08:44,227 | INFO     | werkzeug |  * Debugger PIN: 660-035-175
2025-05-04 10:08:53,402 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 10:08:53] "GET / HTTP/1.1" 200 -
2025-05-04 10:08:53,831 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 10:08:53] "[36mGET /static/icons/googe.png HTTP/1.1[0m" 304 -
2025-05-04 10:08:53,883 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 10:08:53] "[36mGET /static/icons/icon1.JPG HTTP/1.1[0m" 304 -
2025-05-04 10:08:57,888 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 10:08:57] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 10:10:02,212 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 10:10:02] "[32mGET /oauth2callback?state=GAXEzHKdnEsuyyXcXyeP7cTRIvoP8C&code=4/0Ab_5qlnaVY6w4QNBNAcmSyEPUx82lbTx8XeneHcCNciL3cOf6WB0zbTJVHGRKMW1mHtPeA&scope=email%20profile%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=consent HTTP/1.1[0m" 302 -
2025-05-04 10:10:02,222 | INFO     | werkzeug | 127.0.0.1 - - [04/May/2025 10:10:02] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 10:10:40,931 | INFO     | werkzeug |  * Detected change in 'C:\\Users\\Sbongakonke Sfiso\\OneDrive - University of KwaZulu-Natal\\Desktop\\3D Objects\\email_sender_app\\app.py', reloading
2025-05-04 10:10:41,134 | INFO     | werkzeug |  * Restarting with stat
2025-05-04 10:10:48,400  WARNING   werkzeug —  * Debugger is active!
2025-05-04 10:10:48,412  INFO      werkzeug —  * Debugger PIN: 660-035-175
2025-05-04 10:18:37,787  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:18:37] "[32mGET /oauth2callback?state=KeoH8u9BsXkdPPWYp6QY4zSIE19DAD&code=4/0Ab_5qllIzyj5W9-YAdRS6f1aNCvgptVeo_AdJE9m_aIpP4aP9v0NmOrIOm8bEiocOOnsVw&scope=email%20profile%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=consent HTTP/1.1[0m" 302 -
2025-05-04 10:18:38,043  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:18:38] "[32mGET /client/login HTTP/1.1[0m" 302 -
2025-05-04 10:20:24,376  INFO      werkzeug —  * Detected change in 'C:\\Users\\Sbongakonke Sfiso\\OneDrive - University of KwaZulu-Natal\\Desktop\\3D Objects\\email_sender_app\\app.py', reloading
2025-05-04 10:20:25,871 | INFO     | werkzeug |  * Restarting with stat
2025-05-04 10:20:29,891  WARNING   werkzeug —  * Debugger is active!
2025-05-04 10:20:29,916  INFO      werkzeug —  * Debugger PIN: 660-035-175
2025-05-04 10:20:52,270  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 10:20:52,473  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:52] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 10:20:52,776  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:52] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-05-04 10:20:52,882  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:52] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-05-04 10:20:53,031  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:53] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 10:20:53,790  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:53] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 10:20:55,797  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 10:20:55,839  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:55] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 10:20:55,923  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:55] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-05-04 10:20:55,961  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:55] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-05-04 10:20:56,066  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:56] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 10:20:56,260  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:56] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 10:20:57,424  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 10:20:57,556  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:57] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 10:20:57,849  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:57] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-05-04 10:20:57,864  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:57] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-05-04 10:20:57,969  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:57] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 10:20:58,391  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:20:58] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 10:21:32,303  INFO      werkzeug — [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.245.128.60:5000
2025-05-04 10:21:32,328  INFO      werkzeug — [33mPress CTRL+C to quit[0m
2025-05-04 10:21:32,335  INFO      werkzeug —  * Restarting with stat
2025-05-04 10:21:35,690  WARNING   werkzeug —  * Debugger is active!
2025-05-04 10:21:35,707  INFO      werkzeug —  * Debugger PIN: 660-035-175
2025-05-04 10:21:57,060  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 10:21:57,131  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 10:21:57] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 10:21:57,680  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 10:21:57] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-05-04 10:21:57,759  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 10:21:57] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-05-04 10:21:57,896  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 10:21:57] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 10:21:58,256  INFO      werkzeug — 10.245.128.60 - - [04/May/2025 10:21:58] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 10:22:12,765  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 10:22:12,890  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:22:12] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 10:22:13,012  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:22:13] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-05-04 10:22:13,024  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:22:13] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-05-04 10:22:13,213  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:22:13] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-05-04 10:26:19,267  INFO      werkzeug — [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.245.128.60:5000
2025-05-04 10:26:19,271  INFO      werkzeug — [33mPress CTRL+C to quit[0m
2025-05-04 10:26:19,279  INFO      werkzeug —  * Restarting with stat
2025-05-04 10:26:21,745  WARNING   werkzeug —  * Debugger is active!
2025-05-04 10:26:21,783  INFO      werkzeug —  * Debugger PIN: 660-035-175
2025-05-04 10:26:25,022  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 10:26:25,044  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:26:25] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 10:28:53,152  INFO      werkzeug — [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.245.128.60:5000
2025-05-04 10:28:53,156  INFO      werkzeug — [33mPress CTRL+C to quit[0m
2025-05-04 10:28:53,161  INFO      werkzeug —  * Restarting with stat
2025-05-04 10:28:55,599  WARNING   werkzeug —  * Debugger is active!
2025-05-04 10:28:55,614  INFO      werkzeug —  * Debugger PIN: 660-035-175
2025-05-04 10:29:15,934  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 10:29:15,967  INFO      werkzeug — 127.0.0.1 - - [04/May/2025 10:29:15] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 14:14:52,031  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 14:14:52,085  INFO      werkzeug — 10.231.128.108 - - [04/May/2025 14:14:52] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 14:14:58,507  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 14:14:58,555  INFO      werkzeug — 10.231.128.108 - - [04/May/2025 14:14:58] "[35m[1mGET /loginMsg.js HTTP/1.1[0m" 500 -
2025-05-04 14:14:58,574  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 14:14:58,584  INFO      werkzeug — 10.231.128.108 - - [04/May/2025 14:14:58] "[35m[1mGET /cgi/get.cgi?cmd=home_login HTTP/1.1[0m" 500 -
2025-05-04 14:14:59,861  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 14:14:59,865  INFO      werkzeug — 10.231.128.108 - - [04/May/2025 14:14:59] "[35m[1mGET /rootDesc.xml HTTP/1.1[0m" 500 -
2025-05-04 18:06:42,836  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 18:06:42,866  INFO      werkzeug — 10.245.130.186 - - [04/May/2025 18:06:42] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 18:06:49,388  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 18:06:49,397  INFO      werkzeug — 10.245.130.186 - - [04/May/2025 18:06:49] "[35m[1mGET /loginMsg.js HTTP/1.1[0m" 500 -
2025-05-04 18:06:49,416  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 18:06:49,422  INFO      werkzeug — 10.245.130.186 - - [04/May/2025 18:06:49] "[35m[1mGET /cgi/get.cgi?cmd=home_login HTTP/1.1[0m" 500 -
2025-05-04 18:06:52,663  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 18:06:52,667  INFO      werkzeug — 10.245.130.186 - - [04/May/2025 18:06:52] "[35m[1mGET /rootDesc.xml HTTP/1.1[0m" 500 -
2025-05-04 22:05:06,382  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-04 22:05:06,415  INFO      werkzeug — 10.245.130.186 - - [04/May/2025 22:05:06] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-04 22:05:12,888  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 22:05:12,898  INFO      werkzeug — 10.245.130.186 - - [04/May/2025 22:05:12] "[35m[1mGET /loginMsg.js HTTP/1.1[0m" 500 -
2025-05-04 22:05:12,918  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 22:05:12,924  INFO      werkzeug — 10.245.130.186 - - [04/May/2025 22:05:12] "[35m[1mGET /cgi/get.cgi?cmd=home_login HTTP/1.1[0m" 500 -
2025-05-04 22:05:16,485  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-04 22:05:16,489  INFO      werkzeug — 10.245.130.186 - - [04/May/2025 22:05:16] "[35m[1mGET /rootDesc.xml HTTP/1.1[0m" 500 -
2025-05-06 14:43:44,416  INFO      werkzeug — [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.203:5000
2025-05-06 14:43:44,418  INFO      werkzeug — [33mPress CTRL+C to quit[0m
2025-05-06 14:43:44,425  INFO      werkzeug —  * Restarting with stat
2025-05-06 14:43:46,936  WARNING   werkzeug —  * Debugger is active!
2025-05-06 14:43:46,954  INFO      werkzeug —  * Debugger PIN: 543-716-034
2025-05-06 14:44:12,168  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-06 14:44:12,339  INFO      werkzeug — 127.0.0.1 - - [06/May/2025 14:44:12] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-06 14:58:16,880  ERROR     __main__ — Unhandled exception: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\app.py", line 368, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\templates\index.html", line 257, in top-level template code
    <a href="{{ url_for('help') }}">Help Center</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'help'. Did you mean 'help_page' instead?
2025-05-06 14:58:16,911  INFO      werkzeug — 192.168.43.203 - - [06/May/2025 14:58:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-05-06 14:58:17,458  ERROR     __main__ — Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sbongakonke Sfiso\OneDrive - University of KwaZulu-Natal\Desktop\3D Objects\email_sender_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-05-06 14:58:17,502  INFO      werkzeug — 192.168.43.203 - - [06/May/2025 14:58:17] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
2025-05-06 14:59:02,824  INFO      werkzeug —  * Detected change in 'C:\\Users\\Sbongakonke Sfiso\\OneDrive - University of KwaZulu-Natal\\Desktop\\3D Objects\\email_sender_app\\app.py', reloading
2025-05-06 14:59:03,354  INFO      werkzeug —  * Restarting with stat
